CREATE TABLE IF NOT EXISTS `data_mappings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_system` VARCHAR(100) NOT NULL,
  `source_field` VARCHAR(100) NOT NULL,
  `destination_system` VARCHAR(100) NOT NULL,
  `destination_field` VARCHAR(100) NOT NULL,
  `mapping_logic` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
